### ISSUE TITLE
May I please use Awesome Blockchain?

### ISSUE THREAD

**Issue by clozinski** [igorbarinov/awesome-blockchain#4]
I run [blogory.org](http://blogory.org).  It is a free service based on the Awesome Python data.  I wanted to do something similar for Bitcoin.  I see that Awesome Bitcoin is Public Domain.  Thank you.  Is Awesome Blockchain also public domain?  May I please use it in [blogory.org/bitcoin](http://blogory.org/bitcoin)?

**Comment by igorbarinov** [comment]
sure
